services:
  redis:
    image: redis:latest
    container_name: aromi-redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: aromi-redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - redis

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: aromi-search
    ports:
      - "7700:7700"
    volumes:
      - meili-data:/meili_data
    environment:
      - MEILI_MASTER_KEY=aromi-dev

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: aromi-server
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - ./packages/server/.env.production
    depends_on:
      - redis
      - meilisearch

  # workers:
  #   build:
  #     context: .
  #     dockerfile: docker/workers.Dockerfile
  #   container_name: aromi-workers
  #   env_file:
  #     - ./packages/workers/.env.production
  #   depends_on:
  #     - redis
  #     - meilisearch

volumes:
  meili-data:
